let AppConfig =
{
    INITIAL_SHAPE_SIZE: 50,
    INITIAL_SHAPE_COLOR: "#00ff00",
    INITIAL_CELL_SIZE: 100,
    INITIAL_LINE_COLOR: "#000000",
    INITIAL_BACKGROUND_COLOR: "#dee2eb",
    INITIAL_TEXT_COLOR: "#000000",
    INITIAL_TEXT_SIZE: 15
};

export {AppConfig}